### ISSUE TITLE
expectConnack goroutine not exit

### ISSUE THREAD

**Issue by hessonsu** [eclipse/paho.golang#101]
![image](https://user-images.githubusercontent.com/16568034/187618953-a151b884-76d4-472d-87f9-0e21f99d2469.png)

if  connCtx  timeout  
expectConnack not quit

fix bug
var (
		caPacket    *packets.Connack
		caPacketCh  = make(chan *packets.Connack)
		caPacketErr = make(chan error,1)
	)

**Comment by MattBrittan** [comment]
A bit more info on this - the relevant code is:

```
var (
		caPacket    *packets.Connack
		caPacketCh  = make(chan *packets.Connack)
		caPacketErr = make(chan error)
	)
	go c.expectConnack(caPacketCh, caPacketErr)
	select {
	case <-connCtx.Done():
		if ctxErr := connCtx.Err(); ctxErr != nil {
			c.debug.Println(fmt.Sprintf("terminated due to context: %v", ctxErr))
		}
		cleanup()
		return nil, connCtx.Err()
	case err := <-caPacketErr:
		c.debug.Println(err)
		cleanup()
		return nil, err
	case caPacket = <-caPacketCh:
	}
```

so `c.expectConnack` will attempt to send to `caPacketErr` if anything goes wrong. However if the context completes then there will no longer be anything waiting on `caPacketErr` so `c.expectConnack` will block (leaking a go routine).

Possible solutions:
- As suggest add a buffer (but should do the same for `caPacketCh` as that may cause the same issue).
- Pass the context and use select to send to Err and receive fron the context (so if the context is cancelled we can exit without waiting for the send.

**Comment by tomatod** [comment]
hessonsu's pullrequest is stopped by eclipsefdn/eca ... So, Can I work in this issue? 

There are two possible solutions as you say. If it's ok,  I will modify as below according to the first easier solution.

```
var (
  caPacket *packets.Connack
  caPacketCh = make(chan *packets.Connack, 1)
  caPacketErr = make(chan error, 1)
)
```

**Comment by MattBrittan** [comment]
@tomatod I've closed off the pull request (cannot accept without an ECA and the issue I identified above has not been addressed). You are welcome to take a look but please ensure you add a comment saying why the channel is buffered (otherwise others will probably assume its not essential in the future and remove the buffer).

**Comment by tomatod** [comment]
The bellow code is reproduction code of this issue. You can confirm expect Connack's goroutines increase and don't stop by using debugger (you need broker waiting by port 1883).  I will continue to work.

```go
package main

import (
	"context"
	"fmt"
	"net"
	"time"

	"github.com/eclipse/paho.golang/paho"
)

func main() {
	for {
		conn, _ := net.Dial("tcp", ":1883")

		conf := paho.ClientConfig{
			Conn:          conn,
			PacketTimeout: 1,
		}

		cli := paho.NewClient(conf)

		_, err := cli.Connect(
			context.Background(),
			&paho.Connect{
				ClientID:   "test",
				CleanStart: true,
			},
		)
		if err != nil {
			fmt.Println(err)
		}
		time.Sleep(time.Second)
	}
}
```
