### ISSUE TITLE
Changing the password for an existing connection

### ISSUE THREAD

**Issue by dtodor** [eclipse/paho.golang#109]
When using OAuth2 tokens as password, the client connection could fail because the token has expired. In this case, it should be possible to change the password without having to create a new connection. This could be easily accomplished by passing a pointer to the configuration:

https://github.com/eclipse/paho.golang/blob/d63b3b28d25ff73076c8846c92c4d062503e646e/autopaho/auto.go#L169

Any thoughts?

**Comment by MattBrittan** [comment]
Passing a pointer would lead to [race conditions](https://go.dev/doc/articles/race_detector) (the main reason it's not a pointer is to make it clear that users should not change things after passing it to `NewConnection`).

I think that [`SetConnectPacketConfigurator`](https://pkg.go.dev/github.com/eclipse/paho.golang@v0.10.0/autopaho#ClientConfig.SetConnectPacketConfigurator) already provides the functionality you need. If you set this then the function will be called every-time a connection is to be established and you can change the password to be used.

**Comment by dtodor** [comment]
Thanks for the hint, this is what I was looking for.
