### ISSUE TITLE
Connack Typo

### ISSUE THREAD

**Issue by 12bchl** [eclipse/paho.golang#120]
Connack 0x81 duplicate typo

**Comment by MattBrittan** [comment]
Please provide more information (currently this has insufficient info to action).

**Comment by 12bchl** [comment]
https://github.com/eclipse/paho.golang/blob/d63b3b28d25ff73076c8846c92c4d062503e646e/packets/connack.go#L21

ConnackProtocolError should be 0x82

**Comment by tomatod** [comment]
According to spec, It is as follows.

[spec 4.13](http://docs.oasis-open.org/mqtt/mqtt/v5.0/cs02/mqtt-v5.0-cs02.html#_Toc514345530)
> The Reason Codes used for Malformed Packet and Protocol Errors are:
> ·         0x81           Malformed Packet
> ·         0x82           Protocol Error

[spec 2.4](http://docs.oasis-open.org/mqtt/mqtt/v5.0/cs02/mqtt-v5.0-cs02.html#_Toc514345303)


Decimal | Hex | Name | Packets
| -- | -- | -- | -- |
| 129 | 0x81 | Malformed Packet | CONNACK, DISCONNECT
| 130 | 0x82 | Protocol Error | CONNACK, DISCONNECT
