### ISSUE TITLE
Subscribe API makes it impossible to match suback reasons to subscribed topics

### ISSUE THREAD

**Issue by ewirch** [eclipse/paho.golang#123]
Version: 0.10.0

`Client.Subscribe` expects a map containing subscription topics as keys:
```go
Subscriptions map[string]SubscribeOptions
```
Later, these topics are sent to MQTT broker using a for-range loop:
```go
for t, o := range s.Subscriptions {
	writeString(t, &subs)
	subs.WriteByte(o.Pack())
}
```
for-range loop over a map is specified to have no consistent order (["The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next."](https://go.dev/ref/spec)). Thus, the order in which topics are sent to broker is unknown. There is no way, one could correlate order of suback reasons to subscribed topics:
```go
Suback struct {
	Properties *SubackProperties
	Reasons    []byte
}
```

**Comment by MattBrittan** [comment]
Closing this as the underlying issue was corrected some time ago (and included in the last release). `Subscribe` now contains `Subscriptions []SubscribeOptions`.
