### ISSUE TITLE
Ability to refresh connect options during automatic reconnect maybe, supporting Reconnect Handler

### ISSUE THREAD

**Issue by tn185075** [eclipse/paho.golang#127]
**Is your feature request related to a problem? Please describe.**
To be able to fetch new tokens when an automatic reconnect happens. Else, broker rejects the connection saying the token is expired.

**Describe the solution you'd like**
A reconnect handler, which will be invoked on every reconnection happening from client, where I can refresh the token, so the broker would not deny the connection.

**Describe alternatives you've considered**
NA.

**Additional context**
* The broker we communicate with, would accept JWT's for authenticating and authorising clients.
* Whenever a connection is lost, Paho tries to reconnect with the token in the original packet, which would have been expired by then.
* An ability to refresh the authentication options for every reconnect trial at least would be nice to have in these kind of scenarios.
* Much better way, is if we can write our own reconnect handlers which must be processed before performing an automated reconnect.

Please do let me know, if this mechanism already exists.

**Comment by MattBrittan** [comment]
You don't mention how the token is to be sent (MQTT user/password, Websocket header/parameter etc). A few possibilities (have not tested) with autopaho (only really relevant there as paho itself does not reconnect):

* [`SetConnectPacketConfigurator`](https://pkg.go.dev/github.com/eclipse/paho.golang/autopaho#ClientConfig.SetConnectPacketConfigurator) lets you alter the connect packet just before its sent ([example](https://github.com/eclipse/paho.golang/blob/master/autopaho/auto_test.go#L84)).
* `WebSocketCfg` in [`ClientConfig`](https://pkg.go.dev/github.com/eclipse/paho.golang/autopaho#ClientConfig) allows you to provide a custom dialer (so can set headers etc).

Please make an attempt; if you are unable to do this then I may be able to help but don't have much time to respond to requests (especially those that do not include any code).

**Comment by tn185075** [comment]
It's via username and password, I can try it out with `SetConnectPacketConfigurator`. Thanks for pointing out.

**Comment by tn185075** [comment]
I see it available on `auto-paho` package, Can we achieve similar functionality based on original `paho` library?

**Comment by MattBrittan** [comment]
Sorry I don't know what you mean. It's going to be hard to help until you show your attempt.

**Comment by tn185075** [comment]
Apologies, I mean the <a href="https://pkg.go.dev/github.com/eclipse/paho.golang/autopaho#ClientConfig.SetConnectPacketConfigurator"> ClientConfig.SetConnectPacketConfigurator</a> is available in auto-paho's `ClientConfig`, but not in the base `paho.ClientConfig`.

Is there a way I can change the username and password on reconnection with the base Paho package. Unfortunately, I cannot share any code yet.

**Comment by MattBrittan** [comment]
`paho` does not reconnect so it's irrelevant (you need to create a new `paho.Client` if reconnecting). I'm going to close this issue; solutions have been suggested and you have not provided any details as to why they will not work for you.

**Comment by tn185075** [comment]
Thanks for the clarification, We have an internal logic to re-establish connection if any operation is performed against existing connection. I'll continue to look at modifying the connect packet there.

It would have been better, if I can leverage autopaho functionality without the need of migrating my entire code to use it. By that I mean, if the functionality was available on original paho client itself.
