### ISSUE TITLE
Handle publish packet's content retain, duplicate flags always be false when read packet

### ISSUE THREAD

**Issue by BAN1ce** [eclipse/paho.golang#128]
**Describe the bug**
Hi, publish packet's content retain, duplicate flags always be false when receive a setting be true's packet. 
I see that only the QoS flag is processed for the publish packet, and the retain and duplicate are not processed. Is this the design?

```
	if cp.Type == PUBLISH {
		cp.Content.(*Publish).QoS = (cp.Flags & 0x6) >> 1
	}
```

**To reproduce**

```
// run testing 
func TestReadPacketPublish(t *testing.T) {
	rawData := []byte{59, 13, 0, 4, 116, 101, 115, 116, 0, 18, 0, 116, 101, 115, 116}
	c, err := ReadPacket(bufio.NewReader(bytes.NewReader(rawData)))
	require.Nil(t, err)
	assert.Equal(t, true, c.Content.(*Publish).Retain)
	assert.Equal(t, true, c.Content.(*Publish).Duplicate)
	assert.Equal(t, []byte("test"), c.Content.(*Publish).Payload)
	assert.Equal(t, "test", c.Content.(*Publish).Topic)
	assert.Equal(t, uint16(18), c.Content.(*Publish).PacketID)
}
```

**Comment by neiledgar** [comment]
We see this issue where the retain flag is always reported as false. Testing with the changes in the PR resolves this issue. https://github.com/eclipse/paho.golang/pull/129

Are there any plans to merge / rework the PR ?

**Comment by MattBrittan** [comment]
The test above passes with I run it with @master (which should be identical to the latest release). Are you sure you are using the latest code; if so please try the above test (if that works and you still have an issue then your problem is not the same as this one and you should raise a new issue and provide full info).

**Comment by MattBrittan** [comment]
Closing this issue as the test now passes.

**Comment by neiledgar** [comment]
Apologies. I was working from an out of date fork. The test do pass on master
