### ISSUE TITLE
Improve logging for tests

### ISSUE THREAD

**Issue by vishnureddy17** [eclipse/paho.golang#138]
Currently, running the tests results in a bunch of logs being dumped out, making it hard interpret the results test results. It'd be good to at least have the option to suppress them.

**Comment by MattBrittan** [comment]
I believe that #172 addresses this; logging is now via the `test` package and this means that logs are only output when a test fails (which I think will be appropriate in most cases).

**Comment by vishnureddy17** [comment]
Yep, going to close this.
