### ISSUE TITLE
is reconnect  support?

### ISSUE THREAD

**Issue by zrj12345** [eclipse/paho.golang#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alsm** [comment]
No, as the v5 client leaves it to the user to create the socket connection it would not be possible to have the client do reconnect. However it should be possible to call Connect() from the OnDisconnect handler, I don't want to add features like autoreconnect again if possible, they caused a lot of pain in the v3 client. I prefer to allow you to reconnect from the OnDisconnect handler so you can make the best judgement about what to do. Also as the client now presents a synchronous API for publish/subscribe/etc there doesn't seem to be much benefit from auto reconnect as there is no offline buffering.

**Comment by blusewang** [comment]
when mosquitto server restart. `OnDisconnect` not called!
