### ISSUE TITLE
0 Packet Identifier in acknowledgments causes panic

### ISSUE THREAD

**Issue by MattBrittan** [eclipse/paho.golang#145]
**Describe the bug**
When acknowledgments are received `c.MIDs.Get(recv.PacketID())` is run. If the PacketID is 0 this leads to a panic (due to `return m.index[i-1]` in `message_ids.go`.

**To reproduce**
Send a PUBACK with 0 packet ID (occurred whilst I was testing something else). Quick and dirty test to replicate:

```
func TestClientReceiveQoS10ClientID(t *testing.T) {
	rChan := make(chan struct{})
	ts := newTestServer()
	go ts.Run()
	defer ts.Stop()

	c := NewClient(ClientConfig{
		Conn: ts.ClientConn(),
		Router: NewSingleHandlerRouter(func(p *Publish) {
			assert.Equal(t, "test/0", p.Topic)
			assert.Equal(t, "test payload", string(p.Payload))
			assert.Equal(t, byte(0), p.QoS)
			close(rChan)
		}),
	})
	require.NotNil(t, c)
	c.SetDebugLogger(log.New(os.Stderr, "RECEIVEQOS0: ", log.LstdFlags))
	c.SetDebugLogger(log.New(os.Stderr, "RECEIVEQOS1: ", log.LstdFlags))

	c.serverInflight = semaphore.NewWeighted(10000)
	c.clientInflight = semaphore.NewWeighted(10000)
	c.stop = make(chan struct{})
	c.publishPackets = make(chan *packets.Publish)
	go c.incoming()
	go c.PingHandler.Start(c.Conn, 30*time.Second)
	go c.routePublishPackets()

	err := ts.SendPacket(&packets.Puback{
		PacketID:   0,
		ReasonCode: 0,
	})
	require.NoError(t, err)
	time.Sleep(time.Second)
}
```

**Debug output**

```
=== RUN   TestClientReceiveQoS10ClientID
RECEIVEQOS1: 2023/07/26 23:26:34 received PUBACK packet with id 0
RECEIVEQOS1: 2023/07/26 23:26:34 client stopping, incoming stopping
panic: runtime error: index out of range [65535] with length 65535

goroutine 8 [running]:
github.com/eclipse/paho.golang/paho.(*MIDs).Get(0xc00005e4b0?, 0xb333?)
	C:/Users/Matt/Code/Temp/pahotemp/paho.golang/paho/message_ids.go:87 +0xcc
github.com/eclipse/paho.golang/paho.(*Client).incoming(0xc00006ac80)
	C:/Users/Matt/Code/Temp/pahotemp/paho.golang/paho/client.go:459 +0xc0e
created by github.com/eclipse/paho.golang/paho.TestClientReceiveQoS10ClientID
	C:/Users/Matt/Code/Temp/pahotemp/paho.golang/paho/client_test.go:359 +0x66a


Process finished with the exit code 1
```

**Expected behaviour**
Need to review the spec in more detail but I believe that 0 should be a valid packet identifier. Have not looked into this too much (raising this issue as I'm working in other areas so will need to come back to this if no one else picks it up). If this is not permitted by the spec then it should be a protocol violation (not a panic).

**Software used:**

paho.golang @master - added test above.

**Additional context**

**Comment by tomatod** [comment]
The spec is the following. So, 0 Packet Identifier may be invalid.
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901026
```
Each time a Client sends a new SUBSCRIBE, UNSUBSCRIBE,or PUBLISH (where QoS > 0) MQTT Control Packet it MUST assign it a non-zero Packet Identifier that is currently unused [MQTT-2.2.1-3].
```

Nowly MIDs.Request doesn't seem to return 0 Packet Identifier (I haven't confirmed the behavior actually because I can't run program now). I probably remember implementing it such behavior according to original implemention on purpose.
https://github.com/eclipse/paho.golang/blob/master/paho/message_ids.go#L56-L80

But, I also think It's undesirable that Panic is caused by MIDs.Get(0). Because MIDService interface's Get() doesn't return any value, handling seems to be needed to consider.

**Comment by MattBrittan** [comment]
Thanks @tomatod - I thought that the spec indicated that the Packet Identifier must be non-zero somewhere but could not find it last night!

Based on this (and 

>Each time a Server sends a new PUBLISH (with QoS > 0) MQTT Control Packet it MUST assign it a non zero Packet Identifier that is currently unused [MQTT-2.2.1-4].

) I think we can safely say that non-zero packet IDs are not valid within the session state. This means that MIDS should never return a session for `PacketID == 0` thus adding `if i == 0 {return nil}` to the various Mids functions is probably an acceptable solution.

**Comment by tomatod** [comment]
@MattBrittan 
> adding if i == 0 {return nil} to the various Mids functions is probably an acceptable solution.

I agree with the opinion. This behavior is equivalent to the case that a specified id (1-65535) is unused.
