### ISSUE TITLE
What is Client.mu protecting?

### ISSUE THREAD

**Issue by vishnureddy17** [eclipse/paho.golang#148]
In `client.go`, there is a mutex `c.mu`, but it is unclear to me what exactly it's protecting. 

https://github.com/eclipse/paho.golang/blob/6c9185827625a60bd3c139d6ff63fce8846979ed/paho/client.go#L71

**Comment by MattBrittan** [comment]
Looks like it's mainly protecting `c.raCtx` (most obviously) and the channels; for instance:

```
c.mu.Lock()
select {
case <-c.stop:
	c.mu.Unlock()
	return
default:
	c.publishPackets <- pb
	c.mu.Unlock()
}
```

It's use here prevents `Close` from running before `c.publishPackets <- pb` completes. It would probably be possible to simplify this but avoiding deadlocks can be tricky!.

**Comment by vishnureddy17** [comment]
Yep, I see it, thanks!

A potential improvement it so figures out how to remove this. Keeping the issue open for that reason (if you'd rather it be closed, feel free to close it)

**Comment by MattBrittan** [comment]
I don't think we can remove it but it would be worth improving the documentation (it really should be locked before any property of `Client` is changed).

**Comment by vishnureddy17** [comment]
Going to go ahead and close this issue, I don't think it's needed anymore.
