### ISSUE TITLE
On disconnect errchan is left unread, leaks a goroutine.

### ISSUE THREAD

**Issue by phcurtis2** [eclipse/paho.golang#155]
On disconnect errChan is left unread, which leaks a goroutine.

sometimes on an autopaho: connectionManager.Disconnect
Exits the NewConnection.mainLoop: leaking a goroutine via (see hangs comment below)
error.go:
func (e *errorHandler) handleError(err error) {
    e.mu.Lock()
    defer e.mu.Unlock()
    if e.errChan != nil {
        e.debug.Printf("received error: %s", err)
        e.errChan <- err  // (hangs here)
        e.errChan = nil 
    } else {
        e.debug.Printf("received extra error: %s", err)
    }   
}

After a connect has been successful over wired ethernet, disconnect the cable
and invoke a connectionManager.Disconnect, about 1/3 of the time it will leak a goroutine
via waiting on errChan that will not be read in the NewConnection go func since it already exited.

**Expected behaviour**
Don't leak a goroutine.

**Software used:**
paho.golang@v0.11.0

**Comment by MattBrittan** [comment]
Funnily enough I'm adding Autopaho tests at the moment (including adding `go.uber.org/goleak`) and came across the same issue (and a few others; mostly stuff that's probably not used in production). I note your PR adds a delay upon exit; this differs from my approach which is:

```
errChan := make(chan error, 1) // Will be sent one, and only one error per connection (buffered to prevent deadlock)
```

As `errChan` will only ever be sent a maximum of one thing, I felt that making it a buffered channel was a workable solution, and think that I prefer this to the added complexity of a timer. Unfortunately there is no "right" value to set the timer to (and setting it too long would make tests pretty slow). 

Based on the above I'm tempted to stick with my solution (which I was going to push today) but would welcome your thoughts. This issue does point to the wider problem which is that there is currently no way to tell when the `paho` library has fully shutdown (I was tempted to look into wrapping the goroutines with the `WaitGroup` so `paho` would only shut down once all goroutines had terminated).

**Comment by phcurtis2** [comment]
Please commit your buffered channel approach. Look forward to that commit ASAP.
Thanks
