### ISSUE TITLE
ConnectProperties in cp_connect.go has a MaximumQOS field that is not part of the MQTT 5 specification

### ISSUE THREAD

**Issue by vishnureddy17** [eclipse/paho.golang#161]
The MQTT 5 spec doesn't include a MaximumQOS field in CONNECT properties, but it is included as a field.

https://github.com/eclipse/paho.golang/blob/21b4033e32237c844f59fab2a2d90954c01c1a2d/paho/cp_connect.go#L29

**Comment by MattBrittan** [comment]
This ends up as property 36 "Maximum QoS" but that is only valid on CONNACK packets so this looks like a bug.

**Comment by MattBrittan** [comment]
This also needs to be fixed in `properties.go` - 

`PropMaximumQOS:             {CONNECT: {}, CONNACK: {}},` 

should be:

`PropMaximumQOS:             {CONNACK: {}},`
