### ISSUE TITLE
Question - How to use certs in CONNECT packets?

### ISSUE THREAD

**Issue by patilsnr** [eclipse/paho.golang#175]
Can you please provide any guidance on how to use certificates in a CONNECT packet? Is that information stored in `ConnectProperties`, or elsewhere? Apologies if this is not the proper forum to ask about this, and I'm happy to clarify more as needed.

**Comment by MattBrittan** [comment]
>certificates in a CONNECT packet

This is not really answerable; CONNECT packets don't have any specific provision for certificates. Certificates may be utilised when setting fields within the connect packet (e.g. a signed token) but no specific use is mandated in the MQTT spec. They may also be used as part of the [auth workflow](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901217) but, again, the details of this are implementation dependent.

The most common way to use certs is to pass a client cert as part of the TLS transaction (e.g. `TlsCfg` in the [`autopaho` config](https://pkg.go.dev/github.com/eclipse/paho.golang@v0.12.0/autopaho#ClientConfig)).

**Comment by patilsnr** [comment]
thanks for the reply, TlsCfg solved the issue
