### ISSUE TITLE
Release request - missing variables in autopaho.ClientConfig

### ISSUE THREAD

**Issue by ashtonian** [eclipse/paho.golang#176]
**Describe the bug**
https://github.com/eclipse/paho.golang/blob/v0.12.0/autopaho/auto.go vs  https://github.com/eclipse/paho.golang/blob/master/autopaho/auto.go 

I'm a little confused, It looks like the tagged v0.12.0 version doesn't include the qos1/2 change? There are missing variables in the v0.12 that are present on master, and lots of other changes.

**Comment by MattBrittan** [comment]
I think the readme is pretty clear?

>Warning breaking change - Release 0.12 contains a breaking change; see the [release notes](https://github.com/eclipse/paho.golang/releases/tag/v0.12.0).

>**Following** the release of v0.12, major changes have been introduced to the library (https://github.com/eclipse/paho.golang/issues/25). Due to the extent of these changes, it's likely that some users will encounter breaking changes and bugs may have been introduced (managing the session state is quite complex!). Please assist us in testing @master; the change should enable more people to migrate from the v3 client and gets us a lot closer to V1.0! (see notes at the end of this readme).

The changes are only in @master at the moment; generally a large change like this will be in @master for a month before a release is considered (we want plenty of time for testing prior to it being pushed to users by default). Note that I am running @master in production at a number of sites (replacing the V3 client) and have not seen any issues yet.

**Comment by ashtonian** [comment]
yep, you right, sorry I read that quickly and assumed it was all in v0.12
