### ISSUE TITLE
context.AfterFunc unrecognized 

### ISSUE THREAD

**Issue by ashtonian** [eclipse/paho.golang#177]
**Describe the bug**

[`context.AfterFunc()` ](https://github.com/eclipse/paho.golang/blob/master/paho/session/state/state.go#L350) wasn't introduced until v1.21 - I _think_ that means it needs to be reflected in the go mod?

**Comment by MattBrittan** [comment]
Thanks for picking this up (I generally update to the latest version of Go pretty quickly so did not notice). 

Just want to consider whether this is the best approach or if we should replace the use of `AfterFunc` with an alternative (generally want to support the current and previous versions of Go and not require users to be running the latest).

**Comment by MattBrittan** [comment]
I've suggested an alternative approach that retains 1.20 compatibility.
