### ISSUE TITLE
client crashes on connection failure

### ISSUE THREAD

**Issue by SimonT90poe** [eclipse/paho.golang#19]
**Nature of fault:**
The bug was introduced in https://github.com/eclipse/paho.golang/pull/16 when the pinger stop channel creation was moved into the pinger start function. the Start function is called at the end of the connection setup, while any error during connection will cause cleanup function to be called, resulting in the use of an uninitialised channel.

**To reproduce**
using stdoutsub example app, attempt connection to a non existent server. The connection will time out and should have cleaned up and existed with connection error. Instead the crash occurred.

**Debug output**
`goroutine 1 [running]:
github.com/eclipse/paho.golang/paho.(*PingHandler).Stop(0xc4200103c0)
	/home/simon/go/src/github.com/eclipse/paho.golang/paho/pinger.go:91 +0xc8
github.com/eclipse/paho.golang/paho.(*Client).Connect.func1()
	/home/simon/go/src/github.com/eclipse/paho.golang/paho/client.go:142 +0x63
github.com/eclipse/paho.golang/paho.(*Client).Connect(0xc4200b2000, 0x55f160, 0xc42001a0d8, 0xc42005bea0, 0x0, 0x0, 0x0)
	/home/simon/go/src/github.com/eclipse/paho.golang/paho/client.go:217 +0xa38
main.main()
	/home/simon/go/src/github.com/eclipse/paho.golang/paho/cmd/stdoutsub/main.go:55 +0x60a
`
note func1 is the cleanup function assigned at the start of Connect function in client.go.

**Expected behaviour**
Connection error

**Software used:**
master as at 2019/08/02 https://github.com/eclipse/paho.golang/commit/782887d0bc5d7e30d069574aa2c46085e017008a

**Additional context**
The problem goes away if the pinger stop channel is created in Client.NewClient() as was prior to #16. The corresponding channel create would need to be removed from PingHandler.Start()
What isn't clear is if that quick fix is correct in the face of auto-reconnect code calling back in to connect at some later date.
An alternative fix might be to create a constructor for PingHandler where the channel can be created with anything else required, and the Start function behave as is, but be named something more like SetKeepAlive.

**Comment by alsm** [comment]
Thanks for reporting this, it should be fixed in the PR above.
