### ISSUE TITLE
Option to set willMessageExpiry

### ISSUE THREAD

**Issue by abh** [eclipse/paho.golang#200]
The `SetWillMessage` allows for some attributes of the will message, but not for example setting the `MessageExpiry` property. It'd be nice if the API allowed for this (maybe by having `SetWillMessage` or another method allow the user to just set the full packet, instead of individual attributes).

**Comment by MattBrittan** [comment]
Already done as per issue #174 (currently only in @master)

**Comment by MattBrittan** [comment]
Closing this as a solution is already in place.
