### ISSUE TITLE
Question about user properties

### ISSUE THREAD

**Issue by DrmagicE** [eclipse/paho.golang#21]
According to the specification:
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901116
> 38 (0x26) Byte, Identifier of the User Property.
Followed by a UTF-8 String Pair. The User Property is allowed to appear multiple times to represent multiple name, value pairs. The same name is allowed to appear more than once.

There are maybe duplicated key in user properties. It may missing some data if using map to store them.

https://github.com/eclipse/paho.golang/blob/8101db49c24ed22b4fff61152e96761e553d16e9/packets/properties.go#L122

I think change it to slice would be better.
```
User []struct{
	Key, Value string
}
```

**Comment by alsm** [comment]
Thanks for noticing that, that is a pain :grin:
