### ISSUE TITLE
Reauthentication with MQTT5 Enhanced Authentication (AUTH packet exchange) in autopaho

### ISSUE THREAD

**Issue by vishnureddy17** [eclipse/paho.golang#212]
I noticed that autopaho does not support reauthentication MQTT5 enhanced authentication. This may be a feature that users need.

**Comment by MattBrittan** [comment]
This should be supported through `AuthHandler` (see [this PR](https://github.com/eclipse/paho.golang/pull/79)). I've not tried to use it but there is [a test](https://github.com/eclipse/paho.golang/blob/master/paho/client_test.go#L652).

**Comment by vishnureddy17** [comment]
I meant for re-authentication, The `paho` client has an `Authenticate` method so a user can initiate a re-authentication on an already-connected client, but it seems like `autopaho` doesn't have an equivalent. (edited the issue to make it clearer)

**Comment by MattBrittan** [comment]
Cool - as `paho` supports this it should be a very simple change (pretty much copy `Subscribe` but call `paho.Authenticate`).

**Comment by Widgle** [comment]
Could I try this one?

**Comment by MattBrittan** [comment]
@Widgle - go for it; note that you will need to sign the [contributor agreement](https://github.com/eclipse/paho.golang/blob/master/CONTRIBUTING.md#contributor-license-agreement) (if you have not already done so). I will be making a few further changes this week that may impact yours but I'm sure we can make things work.
