### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by Widgle** [eclipse/paho.golang#217]
Hi team! I have been using this library and I'm trying to start contributing to this project now.

Seems [CONTRIBUTING.md](https://github.com/eclipse/paho.golang/blob/master/CONTRIBUTING.md) needs some update.

1. In Project description, link was changed to https://projects.eclipse.org/projects/iot.paho from https://projects.eclipse.org/projects/technology.paho, I think it would be good to change the link even if it works because of redirection.
2. The link in Developer resources doesn't work, because it was changed to https://projects.eclipse.org/projects/iot.paho/developer from https://projects.eclipse.org/projects/technology.paho/developer, and it seems the site no longer has information regarding source code management, builds, coding standards, and so on, so I think it would be better to remove that section.

What do you think about them? I'd like to make a PR for the changes if you guys agree with them.

Thank you!

**Comment by MattBrittan** [comment]
@Widgle go for it - the docs could do with a bit of work.
