### ISSUE TITLE
PublishWithOptions() will not return ErrInvalidArguments when QoS is invalid

### ISSUE THREAD

**Issue by vishnureddy17** [eclipse/paho.golang#232]
https://github.com/eclipse/paho.golang/blob/ef0065fea247d5fb388fa82390cedce694e844e1/paho/client.go#L885

This should have `ErrInvalidArguments` in its tree so the application knows it is a fatal error. This is a very quick fix and I am happy to open a PR for it.

**Comment by MattBrittan** [comment]
>This is a very quick fix and I am happy to open a PR for it.

Please do - keen to get a release out this week and would be nice to have this fixed.

**Comment by vishnureddy17** [comment]
Will open a PR today or tomorrow (US Eastern time). Would you like me to incorporate a fix to https://github.com/eclipse/paho.golang/issues/233 as well? @MattBrittan

**Comment by MattBrittan** [comment]
>Would you like me to incorporate a fix to https://github.com/eclipse/paho.golang/issues/233 as well

Yes please.
