### ISSUE TITLE
Persistence is not implemented

### ISSUE THREAD

**Issue by MattBrittan** [eclipse/paho.golang#25]
**Describe the bug**
The package includes a `Persistence` interface along with two implementations (`noopPersistence ` and `MemoryPersistence`) but these are not currently used. I have classed this as a bug rather than a feature request because it's partially implemented (and therefore likely to be confusing to new users).

**To reproduce**
Attempt to use the Persistence implementations.

**Debug output**
N/A

**Expected behaviour**
Messages persist as per the MQTT spec.

**Software used:**
- Server was - N/A
- Client version 7369e71

**Additional context**
Mentioned in #23

**Comment by MattBrittan** [comment]
I am taking another look at the implementation of persistence. A few initial thoughts:
1. Initially only outgoing persistence will be implemented (on the basis that the PR enabling user control of ACK's will be implemented so it will be possible to effectively use the broker to handle inbound persistence). This will mean that the package will not fully comply with the spec (and QOS 2 will guarantee no duplication) but keeps things simple (it will be possible to add this later).
2.  Persistence handling will be completely user definable. My initial thought is that all inbound and outbound comms will be added to a channel (rather than being handled/transmitted directly) and the routine that processes these messages could be replaced (which would provide maximum flexibility, including the functionality requested in #40).

Anyway thought I should add a note to indicate that there are plans to do this (no guarantee on a time-frame sorry) ; if anyone has any thoughts/requirements then please let me know so I can feed these into the design.

**Comment by yanmxa** [comment]
@MattBrittan Do you have a plan for how long to enable the `persistence` or `cleansession=false` in this repos?

We've been trying to use this session feature recently with this library, and I've also integrated this MQTT protocol into [CloudEvents](https://github.com/cloudevents/sdk-go), maybe more people will pay attention to this later.

**Comment by MattBrittan** [comment]
@yanmxa I'm actually working on it right now. However I don't know if my current attempt will be successful (or, if it is, how long it will take). The challenge is implementing this in a way that keeps the library simple and idiomatic (really want to avoid the complexity of the v3.1 client).

**Comment by ashtonian** [comment]
is there an equivalent clientconfig.SetConnectionLostHandler() ?

**Comment by MattBrittan** [comment]
> SetConnectionLostHandler

Your comment does not seem directly related to this issue? Paho has [`OnClientError`](https://github.com/eclipse/paho.golang/blob/master/paho/client.go#L51) which will be called if there is a network error.
