### ISSUE TITLE
Record and expose ping latency for diagnostics

### ISSUE THREAD

**Issue by samfweb** [eclipse/paho.golang#267]
**Is your feature request related to a problem? Please describe.**
There isn't currently a way to check how long a ping resp took to arrive.

**Describe the solution you'd like**
I'm building an MQTT visualisation client and a user of mine has asked to see the latency of the connection from the client to broker. The PINGREQ/PINGRESP inside Pinger is already occurring and is a perfect place for this. I'd love for it to be recorded and exposed somehow.

**Describe alternatives you've considered**
Alternatively, if I could have some help accessing net.Conn for the connection I can write my one Pinger-esque class to record latency. I'm not sure if this is possible, however.

**Additional context**
Happy to help with a PR if this seems like something that would be useful to others.

**Comment by MattBrittan** [comment]
Write your own [Pinger](https://pkg.go.dev/github.com/eclipse/paho.golang/paho#Pinger). The default pinger will not make the info available, but it's trivial to add to your own implementation. I don't see this as a common requirement so, given there is a fairly simple means of getting the data, don't feel that it's worth includeing as standard. Please note that the `Pinger` is only called in the absence of other traffic (so may not be called on a system with heavy traffic).

**Comment by samfweb** [comment]
I'll do this then. Thanks for the response.

Is there any way to access net.Conn when using autopaho?
Or will I have to manually create a Client, ensure there's an active
network connection and then connect mqtt to access it?

**Comment by MattBrittan** [comment]
>Is there any way to access net.Conn when using autopaho?

Not sure why you would need the `net.Conn` in this case. If you do, the simplest approach is probably to implent your own [`AttemptConnection`](https://pkg.go.dev/github.com/eclipse/paho.golang/autopaho#ClientConfig). This kind of thing is not exposed because it's difficult to use properly (the library may be accessing it concurrently etc - it's easy to introduce deadlocks etc).

**Comment by samfweb** [comment]
Great, I hadn't seen AttemptConnection. That makes it much easier.

I'd love to avoid writing my own but autopaho's connection manager doesn't expose any way to write a packet other than Publish from what I can see.

[Pinger itself uses net.Conn](https://github.com/eclipse/paho.golang/blob/f1fe38b0d4b0ad0347176409c5acdef45b2ff337/paho/pinger.go#L121) to write a PINGREQ packet directly to the server. 

Is there an alternative way to send a PINGREQ?

And how would I go about listening for a PINGRESP [like in the client]?(https://github.com/eclipse/paho.golang/blob/f1fe38b0d4b0ad0347176409c5acdef45b2ff337/paho/pinger.go#L121)?

**Comment by MattBrittan** [comment]
>[Pinger itself uses net.Conn](https://github.com/eclipse/paho.golang/blob/f1fe38b0d4b0ad0347176409c5acdef45b2ff337/paho/pinger.go#L121) to write a PINGREQ packet directly to the server.

Correct - and `Pinger.Run` will be called and passed the new `net.Conn` whenever autopaho creates a new connection. As the implemented of the pinger it's up to you when you send them (still not seeing why you would need to do anything other than just implement the `Pinger` interface).

>And how would I go about listening for a PINGRESP [like in the client](https://github.com/eclipse/paho.golang/blob/f1fe38b0d4b0ad0347176409c5acdef45b2ff337/paho/pinger.go#L121)?

You don't - `PingResp()` will be called when it's received. You need to let `paho` manage the connection (or do something complex, like wrap the connection and capture ping responses - but that would be trickey and seems fairly pointless).

**Comment by samfweb** [comment]
Aha. Didn't realise you could add your own Pinger to ClientConfig. This makes a lot more sense!

Thanks for the help.
