### ISSUE TITLE
paho.Client Unsubscribe failing. Broker rejecting and shutting down connection

### ISSUE THREAD

**Issue by dm180015** [eclipse/paho.golang#30]
Easily reproducible with any call to Unsubscribe. Using HiveMQ mqtt5 broker

_, err = c.Unsubscribe(context.Background(), &paho.Unsubscribe{
		Topics: []string{*topic}})

Fix is:
Unsubscribe.go line 58 (adding Flags: 2)

// WriteTo is the implementation of the interface required function for a packet
func (u *Unsubscribe) WriteTo(w io.Writer) (int64, error) {
	cp := &ControlPacket{FixedHeader: FixedHeader{Type: UNSUBSCRIBE, Flags: 2}}

**Comment by alsm** [comment]
Oops, thanks for catching that.
