### ISSUE TITLE
Subscription Identifier is encoded incorrectly

### ISSUE THREAD

**Issue by ryskiwt** [eclipse/paho.golang#39]
Dear maintainers,

I found `SubscriptionIdentifier` property is encoded as uint32.
https://github.com/eclipse/paho.golang/blob/76d833e84427556b3da4fe902b40b9bbe6956209/packets/properties.go#L185

But OASIS standard says this field's type is `Variable Byte Integer`.
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901029

Is this a bug?

[FYI] I tried to connect some public MQTT5 brokers using this library eclipce/paho.golang 
but brokers did not respond correctly.
- EMQX https://www.emqx.io/mqtt/public-mqtt5-broker
- HiveMQ https://www.hivemq.com/public-mqtt-broker/

Thanks,

Ryosuke

**Comment by alsm** [comment]
Yes this is a bug, thanks for reporting, I will fix it shortly

**Comment by alsm** [comment]
Thanks again, should be resolved
