### ISSUE TITLE
OnDisconnect not call

### ISSUE THREAD

**Issue by a-wing** [eclipse/paho.golang#43]
https://github.com/eclipse/paho.golang/blob/76a1f9a081d13c3e6da7706c7dd3e24c8139d82c/paho/client.go#L378-L387

Only receive `packets.DISCONNECT` call `OnDisconnect()`

Network error not call `OnDisconnect()`

```
[DEBUG]: 2021/01/19 12:15:41 client.go:622: sending QoS0 message
[DEBUG]: 2021/01/19 12:15:43 client.go:400: error called: EOF
[DEBUG]: 2021/01/19 12:15:43 client.go:408: client stopped
[DEBUG]: 2021/01/19 12:15:43 client.go:410: ping stopped
[DEBUG]: 2021/01/19 12:15:43 client.go:412: conn closed
```

But Network error cannot be known

**Need notified to Network error**

**Comment by alsm** [comment]
Being as there is now a server initiated Disconnect I think it is correct that there is callback that only gets called when the server initiates a disconnect. Perhaps I should rename it to OnServerDisconnect and have a separate OnClientError callback for any other error that causes the client to stop.

**Comment by a-wing** [comment]
Maybe use this packet

Reason Code
```
141 | 0x8D | Keep Alive timeout | DISCONNECT
```

**Comment by alsm** [comment]
I'm not going to add something like that if I don't know that that is the reason for the disconnect. And there are many other reasons that could cause the connection to be lost. I think I will try what I suggested above and see how that works.

**Comment by alsm** [comment]
I just realised that I have started handling this in the branch I had and the open PR, it's probably going to change again shortly
