### ISSUE TITLE
An error occurs when the number of messages sent with qos > 0 is greater than 65534

### ISSUE THREAD

**Issue by SetForU** [eclipse/paho.golang#46]
**Describe the bug**
I did a stress test and sent 100000 qos>1 messages. When the number of messages is greater than 65534，sdk will report error "context deadline exceeded".
![image](https://user-images.githubusercontent.com/11474067/105567912-9e63e800-5d70-11eb-9413-707f5ee257b1.png)

And then I check mosquitto log，found error "Client test_mqtt_v5 disconnected due to protocol error."
![image](https://user-images.githubusercontent.com/11474067/105567940-c7847880-5d70-11eb-9b41-49641887354e.png)

In order to discover the cause of the error，I checked the source code.
In paho/message_ids.go:
![image](https://user-images.githubusercontent.com/11474067/105568006-39f55880-5d71-11eb-99b3-d8e7eade5926.png)
When MIDs.index is full, packet id will be returened 0.

But according to mosquitto source code, in src/handle_publish.c, function "int handle__publish(struct mosquitto *context)"
![image](https://user-images.githubusercontent.com/11474067/105568092-c9027080-5d71-11eb-9718-8adc24b051d2.png)
When packet id is 0, will report MOSQ_ERR_PROTOCOL error.

I found MIDs has function Free and Clear, but didn't use.
![image](https://user-images.githubusercontent.com/11474067/105568143-24346300-5d72-11eb-9c16-3d4cd73a7870.png)
I think that calling these functions at the right time will solve this problem.

**Comment by alsm** [comment]
Thanks for reporting this, just noticed I had missed it, I should get it fixed tomorrow
