### ISSUE TITLE
QoS 2 acknowledgement problem

### ISSUE THREAD

**Issue by jbonjean** [eclipse/paho.golang#49]
**Describe the bug**
Messages with QoS 2 seem to not be properly acknowledged (PUBREC).

**To reproduce**
Use the chat sample app from this repo with QoS 2, and observe InFlight window counter increase on the server, but no error on the client side. Messages then start to be dropped when the InFlight window max size is reached.
Another client subscribed to the same topic using the MQTT CLI (from HiveMQ) don't have this issue, InFlight counters stays at 0.

**Expected behaviour**
InFlight window counter should not increase.

**Software used:**
- Client: code from master.
- Server: EMQ X Broker 4.1.1, deployed on k8s via official Helm chart.

**Additional context**
Could not reproduce the issue with QoS 1.

**Comment by MattBrittan** [comment]
Not sure but [this EMQX issue](https://github.com/emqx/emqx/issues/3738) (fix released in v4.2.1) may be relevant?

**Comment by jbonjean** [comment]
It could be relevant, nice catch. I'll check that monday and report back. Thanks.

**Comment by jbonjean** [comment]
Unfortunately this is not the issue, summary of my tests:
- Updated to EMQ X 4.2.7: same problem.
- Switched subscribe to `NoLocal: true`: same problem.
- Tested with Python paho: no problem, InFlight window counter stays at 0.

**Comment by alsm** [comment]
Thanks for checking that, I'll take a closer look

**Comment by jbonjean** [comment]
So I did a comparison of Wireshark traces, and it seems no `PUBCOMP` is sent in response to the server `PUBREL`. I quickly checked the code, and it seems that the only reason for not sending `PUBCOMP` is if `PUBREL` reported an error, but Wireshark shows the reason as success.

I may be completly wrong, but I see in Wireshark the value for success is 0, could it be this code is the cause? https://github.com/eclipse/paho.golang/blob/master/paho/client.go#L372-L374

**Comment by SkiTiSu** [comment]
Same problem, I'm using EMQ X 4.2.5.

**Comment by alsm** [comment]
Yeah, an embarrassingly simple problem.
