### ISSUE TITLE
Minimal working example with ejabberd server

### ISSUE THREAD

**Issue by krabiswabbie** [eclipse/paho.golang#50]
**Describe the bug**
I'm unable to connect with paho.golang to ejabberd server with default configuration (locallly installed & MQTT enabled). This simple code always return "context deadline exceeded" after a few seconds though ejabberd log shows successful connection.

In the same time, I can connect easily with MQTTX client w/o any problems.

**To reproduce**
```
package main

import (
	"context"
	"fmt"
	"net"

	"github.com/eclipse/paho.golang/paho"
)

func main() {
	// Make connection to MQTT host
	conn, err := net.Dial("tcp", "localhost:1883")
	if err != nil {
		println(err.Error())
		return
	}

	// Create MQTT Client
	pc := paho.NewClient()
	pc.Conn = conn

	connectOptions := &paho.Connect{
		KeepAlive:    10,
		CleanStart:   true,
		ClientID:     "testClient",
		Username:     "user2@work",
		Password:     []byte("pass"),
		UsernameFlag: true,
		PasswordFlag: true,
	}

	// Connect Client to MQTT Broker
	res, err := pc.Connect(context.Background(), connectOptions)
	if err != nil {
		println("Failed to connect: " + err.Error())
		return
	}
	if res.ReasonCode != 0 {
		r := fmt.Sprintf("Failed to connect with reason: %d - %s", res.ReasonCode, res.Properties.ReasonString)
		println(r)
		return
	}
	println("Connected to MQTT Broker successfully")
	switch{}
}
```

**Debug output**
paho.golang throw a error after a few seconds:
`Failed to connect: context deadline exceeded`

ejabberd Server shows successful connection:
`
A17:35:45.726 [info] (<0.602.0>) Accepted connection 127.0.0.1:34690 -> 127.0.0.1:1883
17:35:45.727 [info] Accepted MQTT authentication for user2@work/testClient by mnesia backend from 127.0.0.1
17:35:45.727 [info] Opened MQTT session for user2@work/testClient from 127.0.0.1
17:35:55.729 [info] Closing MQTT session for user2@work/testClient from 127.0.0.1: Connection failed: connection closed
`

Internal Paho.Client.Incoming.ReadPacket() function return the following error (catched in debugger)
`
"invalid Prop type 17 for packet 2"
`

**Expected behaviour**
Successfully connected to ejabberd server

**Software used:**
Ubuntu 18.04
ejabberd-21.01 (MQTT 5.0)

**Comment by MattBrittan** [comment]
Please check that you are using the latest version of this library (`go get -u github.com/eclipse/paho.golang`). [This change](https://github.com/eclipse/paho.golang/commit/28e6c406bdb75485040a8d6f1c2b743401171de6#diff-15524f84d9c320bd0a85231c38f258107b3fd86dc42f31d4b84c6a1cac06e01b) on 14th Dec added support for property 17 (SessionExpiryInterval) in the CONACK packet (packet 2) so I suspect you are using an older version? I was going to test this but unfortunately the [test broker](https://docs.ejabberd.im/admin/guide/mqtt/#testing-mqtt-from-the-client-perspective) `mqtt.fluux.io` appears to be down.

**Comment by krabiswabbie** [comment]
Thanks for your answer!
I do use the version 0.9.0 of this library, tried to remove/reinstall, still v.0.9.0 but no luck.
A also failed to connect to mqtt.fluxx.io (the host is actually rejecting connections)

**Comment by MattBrittan** [comment]
Sorry 0.9.0 is almost a year old - try master `go get -u github.com/eclipse/paho.golang@master`

**Comment by krabiswabbie** [comment]
True, after manually upgrading to 0.9.1 it works flawlessly. 
Apparently there is some kind of configuration problem, sorry to have bothered you.
