### ISSUE TITLE
V3 client in the same style

### ISSUE THREAD

**Issue by alsm** [eclipse/paho.golang#6]
A v3 client in the style of the new v5 client should prove to be a more maintainable (and potentially more correct) implementation than the current v3 client at https://github.com/eclipse/paho.mqtt.golang/
Thought needs to be given to the design/integration; it is possible to provide a single client library support both v3 and v5? If possible is it desirable (would it make the code too messy)?

These questions need to be answered before a 1.0 release, thoughts and ideas welcome.

**Comment by juliandroid** [comment]
You could always rewrite v3 by using v5 library (i.e. v3 to be wrapper around v5), so if you fix something in v5 it will be automatically available in v3.

**Comment by jjm011** [comment]
Do you have a rough estimate for V5 support 1.0 release? What is the current status of this release? I am new to V5 but my project requires a golang mqtt client that uses the V5 standard, so I may be able to help if you can list me a few missing points that need to be addressed for the 1.0 stable release.

**Comment by alsm** [comment]
@juliandroid This client is not going to be API compatible with the previous client, and any v3 client here will be the same. There is some commonality between the two that could be shared, I just need to see how much that is and how easily I can share those parts.

**Comment by alsm** [comment]
@jjm011 I don't really, a 1.0 means the API is fixed, I won't be doing that until I've had more feedback from people using it as right now it's pretty much just me using it. If you have time to do some prototyping with the client and provide feedback on it that would be really helpful.

**Comment by juliandroid** [comment]
@alsm What I meant is create a compatible V3 implementation that wraps your new V5.
So, your V3 implementation "import V5" and every method from the V3 relies(calls) on respective V5 method. Of course since V3 and V5 API is not 1:1 you'll still need to add some code to V3, for example dummy "Token" implementation that returns immediately (assuming V5 is synchronous API).
On the plus side you'll have easy to back port features form V5 to V3 that are not required by the V3 standard (like $share). Those could be provided as additional "extended" interface. Also fixing V5 bugs automatically would be fixed in V3.

Personally, I have written a simplified V3 client that maps current V3 paho implementation because I wanted my application to be (integration) testable, which wasn't possible with current V3 since you need a real mqtt broker.

On that matter I would like to request (V5) API that is fully mockable, so I can write application that doesn't need real V5 client and (real) broker. With the V3 I had to (re)implement Client+Callbacks+Message+Token interfaces to be fully independent.

**Comment by alsm** [comment]
An interesting idea but I have no intention of of replicating the old V3 client API here, any V3 support will be in the same API style as the new V5 client. If someone else were interested in offering up such an API compatible implementation I wouldn't mind having it as part of the project though.

The mockable part of the new client is something I've been thinking about, given that all it takes is a net.Conn and the Pinger and Router are pluggable you already need a lot less to use it, if you have some example tests where you've needed a mock client I could look at that would be really helpful.

**Comment by alsm** [comment]
:+1: I'll have a think about what I'd need to do to support that

**Comment by slaesh** [comment]
any progress? :)

**Comment by alsm** [comment]
I don't think this is now really required, the current v3 client is well used and I'm not sure the effort or engineering to try and accommodate a v3 client in here is well is worth it. If someone else wants to have a go I'd look at it but I won't be now.

**Comment by viscropst** [comment]
I tried to make this lib to subscribe and receive the v3's message [here](https://github.com/viscropst/paho.golang/tree/mqttv311-support). If any thing to change or nice to startup a PR, mention me plz.

**Comment by mvrhov** [comment]
@viscropst: just create a PR, I I had an example written with this library first and the decision was made to go with mqtt 3.1.1.
The API for the old version is horrendous.

**Comment by alsm** [comment]
Thanks for looking at this, although I closed the issue as I don't think I really want to do it. Superficially there are some things you can do to make it look like an MQTT v3.1.1 client, but there are edge cases and behaviours that are not compatible and I don't really want to swell this library with a load of conditionals. The other option would be to effectively build a new client specifically for v3.1.1 in the same API style and being honest I don't really want to do that work. If someone wanted to do that and become an eclipse committer to support it I would be happy to help them though.

**Comment by mvrhov** [comment]
@alsm No. like I said, the new client api looks idiomatic, the old client API does not. So I'm not interested in new client looking like old one but this new client having support for 3.1.1. @viscropst did the initial work and it looks quite a small patch to be honest.

**Comment by alsm** [comment]
Yes, I understand. What I'm saying is that superficially it might seem like only a few changes to make this client support 3.1.1 but it will actually be a lot more work to make a client that is fully conformant to both specs. I don't think it can be reasonably done in the same codebase. If @viscropst wants to try I'm more than happy to be proven wrong :grin: and if it works will happily accept it, but what I don't want is to make the current v5 client harder or more awkward to use.
