### ISSUE TITLE
Expose the client.stop channel

### ISSUE THREAD

**Issue by mlmarius** [eclipse/paho.golang#64]
I think that exposing the client.stop channel:

https://github.com/eclipse/paho.golang/blob/master/paho/client.go#L54

This will allow for better options to wrap this client with management logic that would attempt to reconnect when the client loses connection.

What do you think?

**Comment by alsm** [comment]
There is already the OnServerDisconnect and OnClientError callbacks, given that the stop channel is internally functional to the client I don't think it would be sensible to expose to or see that it make much difference to using the provided callbacks.
