### ISSUE TITLE
Bad use cause bug of panic

### ISSUE THREAD

**Issue by IguoChan** [eclipse/paho.golang#66]
**Describe the bug**
Sometimes when my client reconnect to the server, it occurs a panic like that:
``` bash
panic: sync: negative WaitGroup counter

goroutine 35 [running]:
sync.(*WaitGroup).Add(0xd56bd0, 0xffffffffffffffff)
        /usr/local/go/src/sync/waitgroup.go:74 +0x139
sync.(*WaitGroup).Done(0xd56bd0)
        /usr/local/go/src/sync/waitgroup.go:99 +0x34
git-pd.megvii-inc.com/bbu-pd/paho.golang/paho.(*Client).Connect.func2(0xd56b20)
        /home/chenyiguo/go/pkg/mod/git-pd.megvii-inc.com/bbu-pd/paho.golang@v0.9.1-0.20210629050451-f3ca92cabe77/paho/client.go:203 +0x2fe
created by git-pd.megvii-inc.com/bbu-pd/paho.golang/paho.(*Client).Connect
        /home/chenyiguo/go/pkg/mod/git-pd.megvii-inc.com/bbu-pd/paho.golang@v0.9.1-0.20210629050451-f3ca92cabe77/paho/client.go:196 +0x534
```
After my investigation, the bad use of my colleagues is roughly as follows:
``` golang
...
var defaultClient MQTT_V5.Client

func connect() {
        clientConfig := MQTT_V5.ClientConfig{
                Conn: connBroker,
                OnServerDisconnect: func(disconnect *MQTT_V5.Disconnect) {
                        reconnect()
                },
                OnClientError: func(err error) {
                        reconnect()
                },
        }
        defaultClient = *MQTT_V5.NewClient(clientConfig)
        c, err := defaultClient.Connect(...)
        ...
}

func reconnect() {
	for i := 0; i < config.GetMQTTConfig().ReconnectBrokerCount; i++ {
		if err := connect(); err != nil {
			logrus.Infof("mqtt reconnect %d times failed", i+1)
			time.Sleep(config.GetMQTTConfig().ReconnectBrokerIntervalDuration * time.Second)
		} else {
			logrus.Infof("mqtt reconnect succeed")
			return
		}
	}
}
```
The bug will reproduce stably (about 50% probability) when reconnect, because of the goroutine below has not return during first connect, when reconnect, but the `defaultClient ` has be reset, its  `workers` has been set to 0, the `c.workers.Add(1)` set it to 1, then 2 times of `defer c.workers.Done()` will minus 1 to -1.
``` golang
c.debug.Println("starting Incoming")
c.workers.Add(1)
go func() {
        defer c.workers.Done()
        c.Incoming()
}()
```
my prints in your code verifies this：
``` golang
func (c *Client) Connect(ctx context.Context, cp *Connect) (*Connack, error) {
        fmt.Printf("0 %p ",&c.workers)
        fmt.Println("0", c.workers, &c.workers)
        ...
        c.debug.Println("starting Incoming")
        c.workers.Add(1)
        fmt.Printf("1 %p ",&c.workers)
        fmt.Println("1", c.workers, &c.workers)
        go func() {
                fmt.Printf("2 %p ",&c.workers)
                fmt.Println("2", c.workers, &c.workers)
                defer fmt.Println("3", c.workers, &c.workers)
                defer fmt.Printf("3 %p ",&c.workers)
                defer c.workers.Done()
                c.Incoming()
        }()
        fmt.Println("do next")
        ...
```
``` bash
=== RUN   TestConnect
0 0xd56bd0 0 {{} [0 0 0]} &{{} [0 0 0]}
1 0xd56bd0 1 {{} [0 1 0]} &{{} [0 1 0]}
do next
0 0xd56bd0 0 {{} [0 0 0]} &{{} [0 0 0]}
2 0xd56bd0 2 {{} [0 0 0]} &{{} [0 0 0]}
1 0xd56bd0 1 {{} [0 1 0]} &{{} [0 1 0]}
do next
2 0xd56bd0 2 {{} [0 1 0]} &{{} [0 1 0]}
3 0xd56bd0 3 {{} [0 0 0]} &{{} [0 0 0]}
3 0xd56bd0 3 {{} [0 1 0]} &{{} [0 4294967295 0]}
panic: sync: negative WaitGroup counter
```
So, when I change to set `defaultClient` is a pointer like 
``` golang
var defaultClient *MQTT_V5.Client
...
defaultClient = MQTT_V5.NewClient(clientConfig)
```
The bug will not occurs. Because every time I called func `connect`, the `defaultClient` will point to a new object.

But I also have some questions: 
1. If you don’t need to wait for the task to complete, why use WaitGroup？
2. The [Package sync](https://golang.org/pkg/sync/) recommend that `Values containing the types defined in this package should not be copied.`, shold the `workers` be defined as `workers *sync.WaitGroup` better? (Even if it still can't solve the bug when bad use.)

**Additional context**
Strictly speaking, this is not a **bug**, after all, if the usage is better, it will not cause problems like that.

**Comment by alsm** [comment]
1. If you call Disconnect() it does wait for all the workers to complete before returning, not doing so in other situations where the client disconnects is a mistake.
2. the waitgroup is not copied to any other function/struct so it should not make a difference.

As you say the issue comes about as defaultClient is getting reset while other goroutines are still running, but I should ensure they have finished before I call OnServerDisconnect or OnClientError

**Comment by IguoChan** [comment]
My apologize, my version is github.com/eclipse/paho.golang v0.9.1-0.20210205145607-b47408c02ce1, that version dose not use c.workers.Wait(), it‘s too far behind the master. I will consider using the latest version in the future。
