### ISSUE TITLE
autopaho: pass connect credentials, etc?

### ISSUE THREAD

**Issue by samba** [eclipse/paho.golang#68]
Any plans to allow passing of other Connect parameters, such as username and password?

https://github.com/eclipse/paho.golang/blob/a215349036a5852a292890e4fea23585aa19e747/autopaho/net.go#L49-L53

Seems like several of the Connect packet properties would be beneficial to configure: 

https://github.com/eclipse/paho.golang/blob/a215349036a5852a292890e4fea23585aa19e747/paho/cp_connect.go#L7-L17

Should most of those properties be promoted up to the autopaho.ClientConfig and then copied down to each connection?

Alternatively, would it be more suitable to let the autopaho.ClientConfig include a callback method, responsible for generating a *paho.Connect instance?

(I'd be happy to contribute if needed; will be signing ECA shortly.)

**Comment by MattBrittan** [comment]
I probably should have included the username/password (sorry - always use certificates so did not think about it). 

Getting the mix between easy to use for a beginner and fully configurable is difficult to get right. I think that a callback is a good idea (allowing advanced config for those who know what they are doing) but as new users are likely to need the ability to set a user/password I'd suggest adding these directly to `autopaho.ClientConfig` so its very obvious how to set them (`autopaho` should handle the `UsernameFlag` and `PasswordFlag` automatically as this confuses new users).

As ClientConfig is getting more complex I also wonder if the variables (anything new anyway) should be private with a setter provided (would make it easier to make changes in the future without breaking existing users code; we are not yet at v1 so can make breaking changes for the time being). Something like `SetAuth(user, password string)` should work for this.

**Comment by samba** [comment]
For my own case, I've been debating how much I want to abstract the MQTT client out of my own code. Previous iterations used `paho.mqtt.golang/#Client` directly, and migration is somewhat laborious. That complexity of `ClientConfig` is worth managing carefully.

I'll start work on a PR supporting:
- [ ] `SetAuth(user, password string)`
- [ ] `SetConnectPacketBuilder(...) *paho.Connect`
- [ ] `SetWillMessage(topic, payload string, qos byte)` (or similar)

I also need to set Will messages in my case, and as it relates to the Connect packet formulation, I would expect it to require similar behavior.
