### ISSUE TITLE
routing based on Subscription Identifier

### ISSUE THREAD

**Issue by samba** [eclipse/paho.golang#71]
From reading the MQTTv5 specs and other implementations, it seems the `Subscription Identifier` is [intended to facilitate routing][1], when a client has multiple subscriptions that would match a specific message's topic. The broker forwards the message with the attached `Subscription Identifier`, which is provided originally by the client, and should enable the client to associate each forwarded message with the accompanying subscription handler. 

https://github.com/eclipse/paho.golang/blob/a215349036a5852a292890e4fea23585aa19e747/paho/router.go#L93-L97

Seems like this would be the right place to implement that Subscription Identifier logic, to select which routes are applicable for a given message. 

Are there historical reasons why this approach has not been implemented in this library?
Would there be any objection to implementing that approach in the near future?

[1]: https://www.emqx.io/blog/subscription-identifier-and-subscription-options

**Comment by alsm** [comment]
No, there is no particular reason this hasn't been implemented and I am more than happy to have a PR with this function, or look at it myself.

**Comment by zyfdegh** [comment]
Got same problem, a **new tag** need to be released please @alsm 

I'm using v0.10.0 but the router has issue matching shared subscription topic, and it was fixed in this commit
CommitID: fd33e6d2ba8489a1fe9a3d36b447c2198d0af427

Currently switching to master branch solves.

**Comment by MattBrittan** [comment]
Quick summary as the link in the original question is dead...

With MQTT when subscribing you can pass a [subscription identifier](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901166) (an integer between 1 and 268,435,455). When the broker sends a PUBLISH packet it will include the subscription identifier (for the SUBSCRIBE that led to the PUBLISH).

This seems like a fairly niche requirement, which would add complexity (i.e. would need a separate  `make(map[subIdType][]MessageHandler),` and way for the IDs to be registered). As things stand it is fairly easy for users to implement this themselves (take a copy of `paho.StandardRouter` and modify as required; the subscription identifier is available within the `*packets.Publish` passed to `Route`), so my feeling is that there would be little value in adding this to the library.

**Comment by MattBrittan** [comment]
I'm going to close this due to lack of activity. It's a fairly niche requirement and can be implemented via a custom router with minimal effort.
