### ISSUE TITLE
websocket connection failed: tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by saibottob** [eclipse/paho.golang#73]
Hello all,

I am currently trying out this lib here and am currently stuck. Maybe you can guide me on the right way. 
I am using the websocket function from autopaho as shown in the code below. 
When I build and run the project, I get the following error message: 

**panic: websocket connection failed: tls: first record does not look like a TLS handshake**

This happens in /autopaho/net.go:51

What do I wrong? 

Many thanks for your help. 

	broker, _ := url.Parse("wss://test.mosquitto.org:8080")

	config := autopaho.ClientConfig{
		BrokerUrls:        []*url.URL{broker},
		KeepAlive:         10,
		ConnectRetryDelay: 10,
		OnConnectionUp: func(cm *autopaho.ConnectionManager, connAck *paho.Connack) {
			fmt.Println("mqtt connection up")
		},
		OnConnectError: func(err error) { fmt.Printf("error whilst attempting connection: %s\n", err) },
		ClientConfig: paho.ClientConfig{
			OnClientError: func(err error) { fmt.Printf("server requested disconnect: %s\n", err) },
		},
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	cm, err := autopaho.NewConnection(ctx, config)
	if err != nil {
		panic(err)
	}

	// Messages will be handled through the callback so we really just need to wait until a shutdown
	// is requested
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, os.Interrupt)
	signal.Notify(sig, syscall.SIGTERM)

	<-sig
	fmt.Println("signal caught - exiting")

	// We could cancel the context at this point but will call Disconnect instead (this waits for autopaho to shutdown)
	ctx, cancel = context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	_ = cm.Disconnect(ctx)

	fmt.Println("shutdown complete")

**Comment by MattBrittan** [comment]
As per (test.mosquitto.org)[http://test.mosquitto.org/]:

> 8080 : MQTT over WebSockets, unencrypted, unauthenticated
8081 : MQTT over WebSockets, encrypted, unauthenticated

So the issue is as indicated by the error; you are attempting to make a TLS connection to an unencrypted broker port. Try port 8081 or `"ws://test.mosquitto.org:8080`.

**Comment by saibottob** [comment]
Many thanks for your help. 
That solved the _websocket connection failed: tls: first record does not look like a TLS handshake_ but now following error message pops-up: `panic: websocket connection failed: unexpected EOF`. I'm using now _"wss://test.mosquitto.org:8081"_. Is there something else which I should be considering?

**Comment by saibottob** [comment]
Issue was on my side, I forget the /mqtt at the end of the web URL. It is now working. Thanks a lot for your help and your engagement :)
