### ISSUE TITLE
Example of How to Use MQTT5 Challenge/Response Auth

### ISSUE THREAD

**Issue by zer0stars** [eclipse/paho.golang#75]
**Is your feature request related to a problem? Please describe.**
I am having an issue understanding how to specify auth method on connect packet as well as where to implement auth packet response.

**Describe the solution you'd like**
An Example of MQTT5 auth: https://www.hivemq.com/blog/implementing-challenge-response-auth/
**Describe alternatives you've considered**
Tried to find examples but did not find 
**Additional context**

**Comment by MattBrittan** [comment]
I don't believe that this is currently supported. As detailed in [the spec](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Enhanced_authentication) `AUTH` packets are sent in between the `CONNECT` and `CONNACK` (the server may request re authentication at a later time). 

After sending a `CONNECT` this library currently [waits for a CONACK](https://github.com/eclipse/paho.golang/blob/master/paho/client.go#L210) (and only a CONACK) as seen here (`expectConnack` sends an error if anything other than a CONNACK is received).

```go
c.debug.Println("waiting for CONNACK")
var (
	caPacket    *packets.Connack
	caPacketCh  = make(chan *packets.Connack)
	caPacketErr = make(chan error)
)
go c.expectConnack(caPacketCh, caPacketErr)
select {
case <-connCtx.Done():
	if ctxErr := connCtx.Err(); ctxErr != nil {
		c.debug.Println(fmt.Sprintf("terminated due to context: %v", ctxErr))
	}
	cleanup()
	return nil, connCtx.Err()
case err := <-caPacketErr:
	c.debug.Println(err)
	cleanup()
	return nil, err
case caPacket = <-caPacketCh:
}
```

So to support extended authentication this would need to be amended to allow `AUTH` packets to be exchanged between the `CONNECT` and `CONNACK` packets. There is some code to handle [`AUTH` packets](https://github.com/eclipse/paho.golang/blob/master/paho/client.go#L418) packets but this would only work for re-authentication so I believe further work is needed to provide the functionality you are looking for.

**Comment by alsm** [comment]
I'm going to close this issue, if there are still things that are needed please open a new one.
