### ISSUE TITLE
Can paho MQTT client use system trusted ca-certificate to establish connection with a TLS enabled broker (no client auth)

### ISSUE THREAD

**Issue by tn185075** [eclipse/paho.golang#76]
This is more of a question than an issue. Please do let me know. Thanks in advance.

**Comment by MattBrittan** [comment]
Yes - with the base library it's up to you to establish the connection (so, in theory, you can use any connection your broker supports).  [autopaho](https://github.com/eclipse/paho.golang/blob/master/autopaho/net.go#L85) provides a wrapper that takes care of establishing the connection for you (the linked code established a TLS connection). On most platforms Go will use the system CA store by default (see `RootCAs` in [`TLS.Config`](https://pkg.go.dev/crypto/tls#Config)).
