### ISSUE TITLE
How to connect to port 8883?

### ISSUE THREAD

**Issue by fherryfherry** [eclipse/paho.golang#80]
There is no clear documentation / sample how to connect to 8883, is there anyone that have connect to 8883 tls?

Thanks before

My Code :
![image](https://user-images.githubusercontent.com/6733315/140475821-2a588558-bdc8-40de-b982-4c3d7cd1ffff.png)
![image](https://user-images.githubusercontent.com/6733315/140475894-b914f582-203a-44d8-99dc-b8623e6e0f28.png)

And the response is EOF:
![image](https://user-images.githubusercontent.com/6733315/140475953-c57a8355-344c-4e02-b487-9997ffee08a5.png)

Note : 
- I use solace cloud as a broker which only provide port 8883 and 8443 (websocket)

**Comment by alsm** [comment]
This client leaves the connectivity down to the user, but there is the autopaho sub project that aims to provide a wrapper around the common uses of the client, including handling connectivity. You could try using that directly or look at the code on network connections https://github.com/eclipse/paho.golang/blob/master/autopaho/net.go to see if that provides any more ideas. Using the test broker at test.moquitto.org:8883 I can successfully connect and subscribe with just the following
```
	conn, err := tls.Dial("tcp", *server, &tls.Config{
		InsecureSkipVerify: true,
	})
```
replacing net.Dial and adding the tls.Config.
