### ISSUE TITLE
Does paho.golang now support topic  subscription sharing?

### ISSUE THREAD

**Issue by kadisi** [eclipse/paho.golang#83]

**Comment by kadisi** [comment]
cc @alsm

**Comment by alsm** [comment]
There is no specific client support needed for shared subscriptions, but the client does check if you try to make a shared subscription if the server has indicated that they are supported.
As in this client the router and subscribing are decoupled you need to ensure you have configured the message router to handle the expected messages before you make the subscription and exclude the `$share/<sharename>/` component. For example with the StandardRouter you would do
```
client.Router.RegisterHandler("my/shared/topic", msgHandler)
sa, err := c.Subscribe(context.Background(), &paho.Subscribe{
    Subscriptions: map[string]paho.SubscribeOptions{
       "$share/shareGroup/my/shared/topic" : {QoS: 1},
    },
})
```
