### ISSUE TITLE
Does this library support v3.1.1 protocol?

### ISSUE THREAD

**Issue by cmackenzie1** [eclipse/paho.golang#89]
I see some references in the code to protocol version 3, but no way to specify it.

https://github.com/eclipse/paho.golang/blob/master/paho/client.go#L20-L21
https://github.com/eclipse/paho.golang/blob/master/paho/client.go#L211-L212

Could the README.md be updated to reflect the supported protocols?

**Comment by alsm** [comment]
I does not and there are no immediate plans to support v3.1.1. in this library.

**Comment by alsm** [comment]
I think given the edge case disparities between 3.1.1 and 5 support for the former is specifically not a feature that will be supported.
