### ISSUE TITLE
Controll packets written to tls connection from multiple routines are intermingled, due to which currupted packets getting sent to server, and server not able to parse the packets, end up closing client session.

### ISSUE THREAD

**Issue by smpchandru** [eclipse/paho.golang#90]
// TLS connection doesn't implement net.buffersWriter interface
       // so cant use 'writeBuffers' API on tls.Conn.
       // Following condition will not return OK inside buffers.WriteTo function
       //   if wv, ok := w.(buffersWriter); ok {
       //              return wv.writeBuffers(v)
       //   })
       // so end up writing messages by iterating over net.Buffers
       //  for _, b := range *v {
       //      nb, err := w.Write(b)
       //      n += int64(nb)
       //      if err != nil {
       //              v.consume(n)
       //              return n, err
       //      }
       //  }
       // which end up writing partial data(Header,Properties,Paylod) in each iteration
       // which will interleave the packet writes from other go routines.

Logs observed at vernemq server
07:13:45.789 [warning] session stopped abnormally due to '{error,{unexpected_message,{error,cant_parse_properties}}}'
07:13:46.254 [error] CRASH REPORT Process <0.5573.2> with 0 neighbours crashed with reason: no case clause matching {8866,<<>>} in vmq_parser_mqtt5:varint_data/1 line 940

**Comment by MattBrittan** [comment]
I believe that PR #84 addresses this; it adds the comments:

```
ClientConfig struct {
		ClientID string
		// Conn is the connection to broker.
		// BEWARE that most wrapped net.Conn implementations like tls.Conn are
		// not thread safe for writing. To fix, use packets.NewThreadSafeConn
		// wrapper or extend the custom net.Conn struct with sync.Locker.
		Conn          net.Conn
```

So, in summary, wrap your connection with `packets.NewThreadSafeConn`.

**Comment by MattBrittan** [comment]
I'm going to close this because I believe the comment mentioned above addresses the issue.
