### ISSUE TITLE
Router's unit tests fail after merging shared subscriptions fix for router

### ISSUE THREAD

**Issue by bkneis** [eclipse/paho.golang#96]
**Describe the bug**
Running make test now fails a test case after merging https://github.com/eclipse/paho.golang/pull/94

**To reproduce**
Run make test on master

**Debug output**
=== RUN   Test_match
=== RUN   Test_match/basic1
=== RUN   Test_match/basic2
=== RUN   Test_match/plus1
=== RUN   Test_match/plus2
=== RUN   Test_match/plus3
=== RUN   Test_match/plus4
=== RUN   Test_match/hash1
=== RUN   Test_match/hash2
=== RUN   Test_match/hash3
=== RUN   Test_match/hash4
=== RUN   Test_match/share1
    router_test.go:30: match() = false, want true
--- FAIL: Test_match (0.00s)
    --- PASS: Test_match/basic1 (0.00s)
    --- PASS: Test_match/basic2 (0.00s)
    --- PASS: Test_match/plus1 (0.00s)
    --- PASS: Test_match/plus2 (0.00s)
    --- PASS: Test_match/plus3 (0.00s)
    --- PASS: Test_match/plus4 (0.00s)
    --- PASS: Test_match/hash1 (0.00s)
    --- PASS: Test_match/hash2 (0.00s)
    --- PASS: Test_match/hash3 (0.00s)
    --- PASS: Test_match/hash4 (0.00s)
    --- FAIL: Test_match/share1 (0.00s)

**Expected behaviour**
make test should pass

**Comment by MattBrittan** [comment]
Closing this as all tests currently pass (and this has not been updated in a year).
